# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'L:\__current work__\04_Python\OptiSim V0.4.1\ui\dielectric_function.ui'
#
# Created: Fri Jan  8 09:15:42 2016
#      by: PyQt5 UI code generator 5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1102, 852)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("GreekC")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.e0SB = QtWidgets.QDoubleSpinBox(Dialog)
        self.e0SB.setMinimum(-100.0)
        self.e0SB.setObjectName("e0SB")
        self.horizontalLayout_2.addWidget(self.e0SB)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.oscillatorComboB = QtWidgets.QComboBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.oscillatorComboB.sizePolicy().hasHeightForWidth())
        self.oscillatorComboB.setSizePolicy(sizePolicy)
        self.oscillatorComboB.setMinimumSize(QtCore.QSize(150, 0))
        self.oscillatorComboB.setObjectName("oscillatorComboB")
        self.horizontalLayout.addWidget(self.oscillatorComboB)
        self.addOscillator = QtWidgets.QPushButton(Dialog)
        self.addOscillator.setObjectName("addOscillator")
        self.horizontalLayout.addWidget(self.addOscillator)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.listOscillator = QtWidgets.QListWidget(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listOscillator.sizePolicy().hasHeightForWidth())
        self.listOscillator.setSizePolicy(sizePolicy)
        self.listOscillator.setMaximumSize(QtCore.QSize(400, 16777215))
        self.listOscillator.setObjectName("listOscillator")
        self.verticalLayout.addWidget(self.listOscillator)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.detailsLayout = QtWidgets.QVBoxLayout()
        self.detailsLayout.setObjectName("detailsLayout")
        self.verticalLayout_2.addLayout(self.detailsLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.activeOscillatorCB = QtWidgets.QCheckBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.activeOscillatorCB.sizePolicy().hasHeightForWidth())
        self.activeOscillatorCB.setSizePolicy(sizePolicy)
        self.activeOscillatorCB.setObjectName("activeOscillatorCB")
        self.horizontalLayout_3.addWidget(self.activeOscillatorCB)
        self.removeOscillator = QtWidgets.QPushButton(self.groupBox)
        self.removeOscillator.setObjectName("removeOscillator")
        self.horizontalLayout_3.addWidget(self.removeOscillator)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addWidget(self.groupBox)
        self.horizontalLayout_6.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.starteVSB = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.starteVSB.setMinimum(0.1)
        self.starteVSB.setMaximum(10.0)
        self.starteVSB.setSingleStep(0.1)
        self.starteVSB.setObjectName("starteVSB")
        self.horizontalLayout_5.addWidget(self.starteVSB)
        self.starteVLabel = QtWidgets.QLabel(self.groupBox_2)
        self.starteVLabel.setObjectName("starteVLabel")
        self.horizontalLayout_5.addWidget(self.starteVLabel)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.endeVSBLabel = QtWidgets.QLabel(self.groupBox_2)
        self.endeVSBLabel.setObjectName("endeVSBLabel")
        self.horizontalLayout_5.addWidget(self.endeVSBLabel)
        self.endeVSB = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.endeVSB.setMinimum(0.1)
        self.endeVSB.setMaximum(10.0)
        self.endeVSB.setSingleStep(0.1)
        self.endeVSB.setObjectName("endeVSB")
        self.horizontalLayout_5.addWidget(self.endeVSB)
        self.endeVLabel = QtWidgets.QLabel(self.groupBox_2)
        self.endeVLabel.setObjectName("endeVLabel")
        self.horizontalLayout_5.addWidget(self.endeVLabel)
        self.horizontalLayout_4.addWidget(self.groupBox_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.loadReference = QtWidgets.QPushButton(Dialog)
        self.loadReference.setObjectName("loadReference")
        self.horizontalLayout_4.addWidget(self.loadReference)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.dielectricFunctionPlot = MplWidgetDielFunc(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dielectricFunctionPlot.sizePolicy().hasHeightForWidth())
        self.dielectricFunctionPlot.setSizePolicy(sizePolicy)
        self.dielectricFunctionPlot.setObjectName("dielectricFunctionPlot")
        self.verticalLayout_3.addWidget(self.dielectricFunctionPlot)
        self.opticalConstantsPlot = MplWidgetDielFunc(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.opticalConstantsPlot.sizePolicy().hasHeightForWidth())
        self.opticalConstantsPlot.setSizePolicy(sizePolicy)
        self.opticalConstantsPlot.setObjectName("opticalConstantsPlot")
        self.verticalLayout_3.addWidget(self.opticalConstantsPlot)
        self.horizontalLayout_6.addLayout(self.verticalLayout_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_4.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Definition of dielectric function"))
        self.label_3.setText(_translate("Dialog", "define oscillators:"))
        self.label_2.setText(_translate("Dialog", "e0"))
        self.label_4.setText(_translate("Dialog", "oscillator"))
        self.addOscillator.setText(_translate("Dialog", "add"))
        self.label.setText(_translate("Dialog", "list of oscillators"))
        self.groupBox.setTitle(_translate("Dialog", "selected oscillator"))
        self.activeOscillatorCB.setText(_translate("Dialog", "active"))
        self.removeOscillator.setText(_translate("Dialog", "remove"))
        self.groupBox_2.setTitle(_translate("Dialog", "spectral range"))
        self.label_7.setText(_translate("Dialog", "start [eV]:"))
        self.starteVLabel.setText(_translate("Dialog", "TextLabel"))
        self.endeVSBLabel.setText(_translate("Dialog", "end [eV]"))
        self.endeVLabel.setText(_translate("Dialog", "TextLabel"))
        self.loadReference.setText(_translate("Dialog", "load reference"))

from ui.mplwidget_dielFunc import MplWidgetDielFunc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

