# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Work\04_Python\OptiSim\OptiSim\ui\fitting_advanced.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1160, 813)
        Dialog.setSizeGripEnabled(True)
        Dialog.setModal(False)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.referenceListView = QtWidgets.QListView(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.referenceListView.sizePolicy().hasHeightForWidth())
        self.referenceListView.setSizePolicy(sizePolicy)
        self.referenceListView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.referenceListView.setObjectName("referenceListView")
        self.verticalLayout_5.addWidget(self.referenceListView)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.parameterTreeView = QtWidgets.QTreeView(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.parameterTreeView.sizePolicy().hasHeightForWidth())
        self.parameterTreeView.setSizePolicy(sizePolicy)
        self.parameterTreeView.setMinimumSize(QtCore.QSize(300, 0))
        self.parameterTreeView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.parameterTreeView.setObjectName("parameterTreeView")
        self.verticalLayout_6.addWidget(self.parameterTreeView)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.line = QtWidgets.QFrame(self.tab)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.reloadPB = QtWidgets.QPushButton(self.tab)
        self.reloadPB.setObjectName("reloadPB")
        self.horizontalLayout.addWidget(self.reloadPB)
        self.startFittingPB = QtWidgets.QPushButton(self.tab)
        self.startFittingPB.setObjectName("startFittingPB")
        self.horizontalLayout.addWidget(self.startFittingPB)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.tab_2)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.methodCB = QtWidgets.QComboBox(self.tab_2)
        self.methodCB.setObjectName("methodCB")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.methodCB)
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.noOfIterationsSB = QtWidgets.QSpinBox(self.tab_2)
        self.noOfIterationsSB.setMaximum(9999999)
        self.noOfIterationsSB.setObjectName("noOfIterationsSB")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.noOfIterationsSB)
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.toleranceSB = ScientificDoubleSpinBox(self.tab_2)
        self.toleranceSB.setObjectName("toleranceSB")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.toleranceSB)
        self.plotInBetweenCB = QtWidgets.QCheckBox(self.tab_2)
        self.plotInBetweenCB.setText("")
        self.plotInBetweenCB.setChecked(True)
        self.plotInBetweenCB.setObjectName("plotInBetweenCB")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.plotInBetweenCB)
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.verticalLayout_2.addLayout(self.formLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.tabWidget.addTab(self.tab_2, "")
        self.horizontalLayout_4.addWidget(self.tabWidget)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.plotView = MplWidgetDielFunc(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotView.sizePolicy().hasHeightForWidth())
        self.plotView.setSizePolicy(sizePolicy)
        self.plotView.setObjectName("plotView")
        self.verticalLayout_3.addWidget(self.plotView)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.resultTextEdit = QtWidgets.QTextEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resultTextEdit.sizePolicy().hasHeightForWidth())
        self.resultTextEdit.setSizePolicy(sizePolicy)
        self.resultTextEdit.setMinimumSize(QtCore.QSize(0, 100))
        self.resultTextEdit.setReadOnly(True)
        self.resultTextEdit.setObjectName("resultTextEdit")
        self.horizontalLayout_2.addWidget(self.resultTextEdit)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_3.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_3.addWidget(self.pushButton_3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        self.pushButton_3.clicked.connect(Dialog.reject)
        self.pushButton_2.clicked.connect(Dialog.accept)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Adavenced Fitting"))
        self.groupBox_2.setTitle(_translate("Dialog", "select references to fit:"))
        self.groupBox_3.setTitle(_translate("Dialog", "select parameters to fit:"))
        self.reloadPB.setText(_translate("Dialog", "reload original"))
        self.startFittingPB.setText(_translate("Dialog", "fit"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "fitting"))
        self.label.setText(_translate("Dialog", "method:"))
        self.label_2.setText(_translate("Dialog", "max. number of iterations:"))
        self.label_3.setText(_translate("Dialog", "tolerance:"))
        self.label_4.setText(_translate("Dialog", "plot results in between:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "configuration"))
        self.groupBox.setTitle(_translate("Dialog", "fit results"))
        self.pushButton_2.setText(_translate("Dialog", "apply to stack"))
        self.pushButton_3.setText(_translate("Dialog", "close without applying"))

from ui.mplwidget_dielFunc import MplWidgetDielFunc
from ui.scientificspin import ScientificDoubleSpinBox

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

