# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'L:\__current work__\04_Python\OptiSim V0.5.0\ui\mainwindow.ui'
#
# Created: Thu Apr 14 14:05:31 2016
#      by: PyQt5 UI code generator 5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1132, 885)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setWindowTitle("")
        MainWindow.setStyleSheet("")
        MainWindow.setDocumentMode(False)
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AllowNestedDocks|QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks|QtWidgets.QMainWindow.ForceTabbedDocks)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(500, 0))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_17.setSpacing(0)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.mdiArea = QtWidgets.QMdiArea(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mdiArea.sizePolicy().hasHeightForWidth())
        self.mdiArea.setSizePolicy(sizePolicy)
        self.mdiArea.setMinimumSize(QtCore.QSize(0, 150))
        self.mdiArea.setAutoFillBackground(False)
        self.mdiArea.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.mdiArea.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.mdiArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.mdiArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        brush = QtGui.QBrush(QtGui.QColor(160, 160, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        self.mdiArea.setBackground(brush)
        self.mdiArea.setViewMode(QtWidgets.QMdiArea.SubWindowView)
        self.mdiArea.setDocumentMode(False)
        self.mdiArea.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.mdiArea.setObjectName("mdiArea")
        self.verticalLayout_17.addWidget(self.mdiArea)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1132, 21))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.dockStackSetup = QtWidgets.QDockWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockStackSetup.sizePolicy().hasHeightForWidth())
        self.dockStackSetup.setSizePolicy(sizePolicy)
        self.dockStackSetup.setMinimumSize(QtCore.QSize(486, 381))
        self.dockStackSetup.setMaximumSize(QtCore.QSize(524287, 524287))
        self.dockStackSetup.setAutoFillBackground(True)
        self.dockStackSetup.setStyleSheet("")
        self.dockStackSetup.setFloating(False)
        self.dockStackSetup.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.dockStackSetup.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.dockStackSetup.setObjectName("dockStackSetup")
        self.dockWidgetContents = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidgetContents.sizePolicy().hasHeightForWidth())
        self.dockWidgetContents.setSizePolicy(sizePolicy)
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.splitter = QtWidgets.QSplitter(self.dockWidgetContents)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.scrollArea = QtWidgets.QScrollArea(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setAutoFillBackground(True)
        self.scrollArea.setStyleSheet("")
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 452, 721))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.scrollAreaWidgetContents)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.StackNameEdit = QtWidgets.QLineEdit(self.tab_2)
        self.StackNameEdit.setObjectName("StackNameEdit")
        self.horizontalLayout_5.addWidget(self.StackNameEdit)
        self.verticalLayout_15.addLayout(self.horizontalLayout_5)
        self.StackFrame = QtWidgets.QFrame(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StackFrame.sizePolicy().hasHeightForWidth())
        self.StackFrame.setSizePolicy(sizePolicy)
        self.StackFrame.setMinimumSize(QtCore.QSize(0, 0))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.StackFrame.setPalette(palette)
        self.StackFrame.setAutoFillBackground(True)
        self.StackFrame.setStyleSheet("")
        self.StackFrame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.StackFrame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.StackFrame.setLineWidth(11)
        self.StackFrame.setObjectName("StackFrame")
        self.verticalStackLayout = QtWidgets.QVBoxLayout(self.StackFrame)
        self.verticalStackLayout.setSpacing(0)
        self.verticalStackLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalStackLayout.setContentsMargins(20, 20, 20, 20)
        self.verticalStackLayout.setObjectName("verticalStackLayout")
        self.verticalLayout_15.addWidget(self.StackFrame)
        self.groupBox = QtWidgets.QGroupBox(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 600))
        self.groupBox.setStyleSheet("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 2, 0, 1, 1)
        self.layerNameField = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.layerNameField.sizePolicy().hasHeightForWidth())
        self.layerNameField.setSizePolicy(sizePolicy)
        self.layerNameField.setObjectName("layerNameField")
        self.gridLayout_2.addWidget(self.layerNameField, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(50, 0))
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 3, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.layerThicknessSB = QtWidgets.QSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.layerThicknessSB.sizePolicy().hasHeightForWidth())
        self.layerThicknessSB.setSizePolicy(sizePolicy)
        self.layerThicknessSB.setMaximum(999999)
        self.layerThicknessSB.setObjectName("layerThicknessSB")
        self.horizontalLayout_2.addWidget(self.layerThicknessSB)
        self.layerThicknessUnit = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.layerThicknessUnit.sizePolicy().hasHeightForWidth())
        self.layerThicknessUnit.setSizePolicy(sizePolicy)
        self.layerThicknessUnit.setMinimumSize(QtCore.QSize(20, 0))
        self.layerThicknessUnit.setObjectName("layerThicknessUnit")
        self.horizontalLayout_2.addWidget(self.layerThicknessUnit)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 3, 1, 1, 1)
        self.colorButton = QtWidgets.QPushButton(self.groupBox)
        self.colorButton.setObjectName("colorButton")
        self.gridLayout_2.addWidget(self.colorButton, 2, 2, 1, 1)
        self.thickLayerCB = QtWidgets.QCheckBox(self.groupBox)
        self.thickLayerCB.setObjectName("thickLayerCB")
        self.gridLayout_2.addWidget(self.thickLayerCB, 3, 2, 1, 1)
        self.verticalLayout_18.addLayout(self.gridLayout_2)
        self.tabWidget = QtWidgets.QTabWidget(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setObjectName("tabWidget")
        self.opticsTab = QtWidgets.QWidget()
        self.opticsTab.setObjectName("opticsTab")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.opticsTab)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox_2 = QtWidgets.QGroupBox(self.opticsTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_4.addWidget(self.label_8)
        self.criSourceSelection = QtWidgets.QComboBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.criSourceSelection.sizePolicy().hasHeightForWidth())
        self.criSourceSelection.setSizePolicy(sizePolicy)
        self.criSourceSelection.setObjectName("criSourceSelection")
        self.horizontalLayout_4.addWidget(self.criSourceSelection)
        self.verticalLayout_7.addLayout(self.horizontalLayout_4)
        self.stackedWidget = QtWidgets.QStackedWidget(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_11 = QtWidgets.QLabel(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_10.addWidget(self.label_11)
        self.criDBList = QtWidgets.QListWidget(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.criDBList.sizePolicy().hasHeightForWidth())
        self.criDBList.setSizePolicy(sizePolicy)
        self.criDBList.setObjectName("criDBList")
        self.verticalLayout_10.addWidget(self.criDBList)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_12 = QtWidgets.QLabel(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_3.addWidget(self.label_12)
        self.criFileEdit = QtWidgets.QLineEdit(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.criFileEdit.sizePolicy().hasHeightForWidth())
        self.criFileEdit.setSizePolicy(sizePolicy)
        self.criFileEdit.setObjectName("criFileEdit")
        self.horizontalLayout_3.addWidget(self.criFileEdit)
        self.criFilePathButton = QtWidgets.QPushButton(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.criFilePathButton.sizePolicy().hasHeightForWidth())
        self.criFilePathButton.setSizePolicy(sizePolicy)
        self.criFilePathButton.setObjectName("criFilePathButton")
        self.horizontalLayout_3.addWidget(self.criFilePathButton)
        self.verticalLayout_11.addLayout(self.horizontalLayout_3)
        self.criFileGroupBox = QtWidgets.QGroupBox(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.criFileGroupBox.sizePolicy().hasHeightForWidth())
        self.criFileGroupBox.setSizePolicy(sizePolicy)
        self.criFileGroupBox.setCheckable(True)
        self.criFileGroupBox.setChecked(False)
        self.criFileGroupBox.setObjectName("criFileGroupBox")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.criFileGroupBox)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_13 = QtWidgets.QLabel(self.criFileGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_6.addWidget(self.label_13)
        self.criFileSpinBox = QtWidgets.QDoubleSpinBox(self.criFileGroupBox)
        self.criFileSpinBox.setSingleStep(0.1)
        self.criFileSpinBox.setObjectName("criFileSpinBox")
        self.horizontalLayout_6.addWidget(self.criFileSpinBox)
        self.verticalLayout_11.addWidget(self.criFileGroupBox)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.page_3)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setHorizontalSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_14 = QtWidgets.QLabel(self.page_3)
        self.label_14.setObjectName("label_14")
        self.gridLayout_4.addWidget(self.label_14, 0, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.page_3)
        self.label_15.setObjectName("label_15")
        self.gridLayout_4.addWidget(self.label_15, 1, 0, 1, 1)
        self.criConstantkEdit = QtWidgets.QDoubleSpinBox(self.page_3)
        self.criConstantkEdit.setSingleStep(0.1)
        self.criConstantkEdit.setObjectName("criConstantkEdit")
        self.gridLayout_4.addWidget(self.criConstantkEdit, 1, 1, 1, 1)
        self.criConstantnEdit = QtWidgets.QDoubleSpinBox(self.page_3)
        self.criConstantnEdit.setSingleStep(0.1)
        self.criConstantnEdit.setObjectName("criConstantnEdit")
        self.gridLayout_4.addWidget(self.criConstantnEdit, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem1, 2, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_3)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page_6)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_18 = QtWidgets.QLabel(self.page_6)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_12.addWidget(self.label_18)
        self.gradingFunctionInput = QtWidgets.QLineEdit(self.page_6)
        self.gradingFunctionInput.setObjectName("gradingFunctionInput")
        self.horizontalLayout_12.addWidget(self.gradingFunctionInput)
        self.gradingFilesButton = QtWidgets.QPushButton(self.page_6)
        self.gradingFilesButton.setObjectName("gradingFilesButton")
        self.horizontalLayout_12.addWidget(self.gradingFilesButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_12)
        self.gradingPlot = MplWidgetSimple(self.page_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gradingPlot.sizePolicy().hasHeightForWidth())
        self.gradingPlot.setSizePolicy(sizePolicy)
        self.gradingPlot.setMinimumSize(QtCore.QSize(0, 0))
        self.gradingPlot.setObjectName("gradingPlot")
        self.verticalLayout_5.addWidget(self.gradingPlot)
        self.stackedWidget.addWidget(self.page_6)
        self.page_8 = QtWidgets.QWidget()
        self.page_8.setObjectName("page_8")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.page_8)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.defineDielectricFunc = QtWidgets.QPushButton(self.page_8)
        self.defineDielectricFunc.setObjectName("defineDielectricFunc")
        self.verticalLayout_19.addWidget(self.defineDielectricFunc)
        self.dielectricPlot = MplWidgetSimple(self.page_8)
        self.dielectricPlot.setObjectName("dielectricPlot")
        self.verticalLayout_19.addWidget(self.dielectricPlot)
        self.stackedWidget.addWidget(self.page_8)
        self.verticalLayout_7.addWidget(self.stackedWidget)
        self.showCRI = QtWidgets.QPushButton(self.groupBox_2)
        self.showCRI.setMinimumSize(QtCore.QSize(100, 0))
        self.showCRI.setObjectName("showCRI")
        self.verticalLayout_7.addWidget(self.showCRI)
        self.extractBandgapPB = QtWidgets.QPushButton(self.groupBox_2)
        self.extractBandgapPB.setObjectName("extractBandgapPB")
        self.verticalLayout_7.addWidget(self.extractBandgapPB)
        self.verticalLayout_6.addWidget(self.groupBox_2)
        self.sroughGroup = QtWidgets.QGroupBox(self.opticsTab)
        self.sroughGroup.setCheckable(True)
        self.sroughGroup.setChecked(False)
        self.sroughGroup.setObjectName("sroughGroup")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.sroughGroup)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_7 = QtWidgets.QLabel(self.sroughGroup)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 0, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.sroughGroup)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 1, 0, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.hazeRSlider = QtWidgets.QSlider(self.sroughGroup)
        self.hazeRSlider.setMaximum(100)
        self.hazeRSlider.setSingleStep(1)
        self.hazeRSlider.setPageStep(1)
        self.hazeRSlider.setProperty("value", 0)
        self.hazeRSlider.setOrientation(QtCore.Qt.Horizontal)
        self.hazeRSlider.setObjectName("hazeRSlider")
        self.horizontalLayout_9.addWidget(self.hazeRSlider)
        self.hazeRLabel = QtWidgets.QLabel(self.sroughGroup)
        self.hazeRLabel.setObjectName("hazeRLabel")
        self.horizontalLayout_9.addWidget(self.hazeRLabel)
        self.gridLayout_3.addLayout(self.horizontalLayout_9, 1, 1, 1, 1)
        self.sroughThicknessEdit = QtWidgets.QSpinBox(self.sroughGroup)
        self.sroughThicknessEdit.setMaximum(1000)
        self.sroughThicknessEdit.setObjectName("sroughThicknessEdit")
        self.gridLayout_3.addWidget(self.sroughThicknessEdit, 0, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.sroughGroup)
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 2, 0, 1, 1)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.hazeTSlider = QtWidgets.QSlider(self.sroughGroup)
        self.hazeTSlider.setMaximum(100)
        self.hazeTSlider.setOrientation(QtCore.Qt.Horizontal)
        self.hazeTSlider.setObjectName("hazeTSlider")
        self.horizontalLayout_17.addWidget(self.hazeTSlider)
        self.hazeTLabel = QtWidgets.QLabel(self.sroughGroup)
        self.hazeTLabel.setObjectName("hazeTLabel")
        self.horizontalLayout_17.addWidget(self.hazeTLabel)
        self.gridLayout_3.addLayout(self.horizontalLayout_17, 2, 1, 1, 1)
        self.verticalLayout_6.addWidget(self.sroughGroup)
        self.tabWidget.addTab(self.opticsTab, "")
        self.electricsTab = QtWidgets.QWidget()
        self.electricsTab.setObjectName("electricsTab")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.electricsTab)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.groupBox_3 = QtWidgets.QGroupBox(self.electricsTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_7.addWidget(self.label_9)
        self.collectionSelection = QtWidgets.QComboBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.collectionSelection.sizePolicy().hasHeightForWidth())
        self.collectionSelection.setSizePolicy(sizePolicy)
        self.collectionSelection.setObjectName("collectionSelection")
        self.horizontalLayout_7.addWidget(self.collectionSelection)
        self.verticalLayout_8.addLayout(self.horizontalLayout_7)
        self.colSourceArea = QtWidgets.QStackedWidget(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colSourceArea.sizePolicy().hasHeightForWidth())
        self.colSourceArea.setSizePolicy(sizePolicy)
        self.colSourceArea.setObjectName("colSourceArea")
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.page_4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_17 = QtWidgets.QLabel(self.page_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_10.addWidget(self.label_17)
        self.colFunctionInput = QtWidgets.QLineEdit(self.page_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colFunctionInput.sizePolicy().hasHeightForWidth())
        self.colFunctionInput.setSizePolicy(sizePolicy)
        self.colFunctionInput.setObjectName("colFunctionInput")
        self.horizontalLayout_10.addWidget(self.colFunctionInput)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.colSourceArea.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.page_5)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.SCRtop = QtWidgets.QRadioButton(self.page_5)
        self.SCRtop.setChecked(True)
        self.SCRtop.setObjectName("SCRtop")
        self.gridLayout_6.addWidget(self.SCRtop, 0, 2, 1, 1)
        self.diffLengthSB = QtWidgets.QSpinBox(self.page_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.diffLengthSB.sizePolicy().hasHeightForWidth())
        self.diffLengthSB.setSizePolicy(sizePolicy)
        self.diffLengthSB.setMinimum(1)
        self.diffLengthSB.setMaximum(99999)
        self.diffLengthSB.setObjectName("diffLengthSB")
        self.gridLayout_6.addWidget(self.diffLengthSB, 1, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.page_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        self.label_22.setObjectName("label_22")
        self.gridLayout_6.addWidget(self.label_22, 0, 0, 1, 1)
        self.SCRwidthSB = QtWidgets.QSpinBox(self.page_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SCRwidthSB.sizePolicy().hasHeightForWidth())
        self.SCRwidthSB.setSizePolicy(sizePolicy)
        self.SCRwidthSB.setMaximum(99999)
        self.SCRwidthSB.setObjectName("SCRwidthSB")
        self.gridLayout_6.addWidget(self.SCRwidthSB, 0, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.page_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_23.sizePolicy().hasHeightForWidth())
        self.label_23.setSizePolicy(sizePolicy)
        self.label_23.setObjectName("label_23")
        self.gridLayout_6.addWidget(self.label_23, 1, 0, 1, 1)
        self.collectionGradingSB = QtWidgets.QDoubleSpinBox(self.page_5)
        self.collectionGradingSB.setDecimals(1)
        self.collectionGradingSB.setMaximum(10000000.0)
        self.collectionGradingSB.setObjectName("collectionGradingSB")
        self.gridLayout_6.addWidget(self.collectionGradingSB, 3, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.page_5)
        self.label_19.setObjectName("label_19")
        self.gridLayout_6.addWidget(self.label_19, 3, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.page_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.gridLayout_6.addWidget(self.label_4, 2, 0, 1, 1)
        self.recVelLE = ScientificDoubleSpinBox(self.page_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.recVelLE.sizePolicy().hasHeightForWidth())
        self.recVelLE.setSizePolicy(sizePolicy)
        self.recVelLE.setObjectName("recVelLE")
        self.gridLayout_6.addWidget(self.recVelLE, 2, 1, 1, 1)
        self.SCRbottom = QtWidgets.QRadioButton(self.page_5)
        self.SCRbottom.setObjectName("SCRbottom")
        self.gridLayout_6.addWidget(self.SCRbottom, 1, 2, 1, 1)
        self.verticalLayout_20.addLayout(self.gridLayout_6)
        self.colSourceArea.addWidget(self.page_5)
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.colSourceArea.addWidget(self.page_7)
        self.verticalLayout_8.addWidget(self.colSourceArea)
        self.collectionPlot = MplWidgetSimple(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.collectionPlot.sizePolicy().hasHeightForWidth())
        self.collectionPlot.setSizePolicy(sizePolicy)
        self.collectionPlot.setMinimumSize(QtCore.QSize(0, 0))
        self.collectionPlot.setObjectName("collectionPlot")
        self.verticalLayout_8.addWidget(self.collectionPlot)
        self.verticalLayout_9.addWidget(self.groupBox_3)
        self.tabWidget.addTab(self.electricsTab, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.constantPointsRB = QtWidgets.QRadioButton(self.groupBox_5)
        self.constantPointsRB.setChecked(False)
        self.constantPointsRB.setObjectName("constantPointsRB")
        self.horizontalLayout_15.addWidget(self.constantPointsRB)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem2)
        self.constantPointsSB = QtWidgets.QSpinBox(self.groupBox_5)
        self.constantPointsSB.setEnabled(False)
        self.constantPointsSB.setMinimum(1)
        self.constantPointsSB.setMaximum(9999)
        self.constantPointsSB.setObjectName("constantPointsSB")
        self.horizontalLayout_15.addWidget(self.constantPointsSB)
        self.verticalLayout_12.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.constantDistRB = QtWidgets.QRadioButton(self.groupBox_5)
        self.constantDistRB.setObjectName("constantDistRB")
        self.horizontalLayout_16.addWidget(self.constantDistRB)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem3)
        self.constantDistSB = QtWidgets.QSpinBox(self.groupBox_5)
        self.constantDistSB.setEnabled(False)
        self.constantDistSB.setMinimum(1)
        self.constantDistSB.setMaximum(100)
        self.constantDistSB.setObjectName("constantDistSB")
        self.horizontalLayout_16.addWidget(self.constantDistSB)
        self.verticalLayout_12.addLayout(self.horizontalLayout_16)
        self.autoDistRB = QtWidgets.QRadioButton(self.groupBox_5)
        self.autoDistRB.setObjectName("autoDistRB")
        self.verticalLayout_12.addWidget(self.autoDistRB)
        self.verticalLayout_14.addWidget(self.groupBox_5)
        self.meshLabel = QtWidgets.QLabel(self.tab)
        self.meshLabel.setObjectName("meshLabel")
        self.verticalLayout_14.addWidget(self.meshLabel)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.verticalLayout_14.addItem(spacerItem4)
        self.tabWidget.addTab(self.tab, "")
        self.verticalLayout_18.addWidget(self.tabWidget)
        self.verticalLayout_15.addWidget(self.groupBox)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_15.addItem(spacerItem5)
        self.tabWidget_2.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout.setObjectName("gridLayout")
        self.calcGenerationCB = QtWidgets.QCheckBox(self.groupBox_6)
        self.calcGenerationCB.setEnabled(False)
        self.calcGenerationCB.setObjectName("calcGenerationCB")
        self.gridLayout.addWidget(self.calcGenerationCB, 5, 0, 1, 1)
        self.calcStackOpticsCB = QtWidgets.QCheckBox(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calcStackOpticsCB.sizePolicy().hasHeightForWidth())
        self.calcStackOpticsCB.setSizePolicy(sizePolicy)
        self.calcStackOpticsCB.setObjectName("calcStackOpticsCB")
        self.gridLayout.addWidget(self.calcStackOpticsCB, 1, 0, 1, 1)
        self.calcFieldIntensityCB = QtWidgets.QCheckBox(self.groupBox_6)
        self.calcFieldIntensityCB.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calcFieldIntensityCB.sizePolicy().hasHeightForWidth())
        self.calcFieldIntensityCB.setSizePolicy(sizePolicy)
        self.calcFieldIntensityCB.setObjectName("calcFieldIntensityCB")
        self.gridLayout.addWidget(self.calcFieldIntensityCB, 2, 0, 1, 1)
        self.calcLayerwiseOpticsCB = QtWidgets.QCheckBox(self.groupBox_6)
        self.calcLayerwiseOpticsCB.setEnabled(False)
        self.calcLayerwiseOpticsCB.setObjectName("calcLayerwiseOpticsCB")
        self.gridLayout.addWidget(self.calcLayerwiseOpticsCB, 3, 0, 1, 1)
        self.plotFieldIntensityCB = QtWidgets.QCheckBox(self.groupBox_6)
        self.plotFieldIntensityCB.setEnabled(False)
        self.plotFieldIntensityCB.setText("")
        self.plotFieldIntensityCB.setObjectName("plotFieldIntensityCB")
        self.gridLayout.addWidget(self.plotFieldIntensityCB, 2, 1, 1, 1)
        self.calcQECB = QtWidgets.QCheckBox(self.groupBox_6)
        self.calcQECB.setEnabled(False)
        self.calcQECB.setObjectName("calcQECB")
        self.gridLayout.addWidget(self.calcQECB, 4, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.groupBox_6)
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 0, 1, 1, 1)
        self.plotStackOpticsCB = QtWidgets.QCheckBox(self.groupBox_6)
        self.plotStackOpticsCB.setEnabled(False)
        self.plotStackOpticsCB.setText("")
        self.plotStackOpticsCB.setObjectName("plotStackOpticsCB")
        self.gridLayout.addWidget(self.plotStackOpticsCB, 1, 1, 1, 1)
        self.calcEllipsometryCB = QtWidgets.QCheckBox(self.groupBox_6)
        self.calcEllipsometryCB.setEnabled(True)
        self.calcEllipsometryCB.setObjectName("calcEllipsometryCB")
        self.gridLayout.addWidget(self.calcEllipsometryCB, 6, 0, 1, 1)
        self.plotLayerwiseOpticsCB = QtWidgets.QCheckBox(self.groupBox_6)
        self.plotLayerwiseOpticsCB.setEnabled(False)
        self.plotLayerwiseOpticsCB.setText("")
        self.plotLayerwiseOpticsCB.setObjectName("plotLayerwiseOpticsCB")
        self.gridLayout.addWidget(self.plotLayerwiseOpticsCB, 3, 1, 1, 1)
        self.plotQECB = QtWidgets.QCheckBox(self.groupBox_6)
        self.plotQECB.setEnabled(False)
        self.plotQECB.setText("")
        self.plotQECB.setObjectName("plotQECB")
        self.gridLayout.addWidget(self.plotQECB, 4, 1, 1, 1)
        self.plotGenerationCB = QtWidgets.QCheckBox(self.groupBox_6)
        self.plotGenerationCB.setEnabled(False)
        self.plotGenerationCB.setText("")
        self.plotGenerationCB.setObjectName("plotGenerationCB")
        self.gridLayout.addWidget(self.plotGenerationCB, 5, 1, 1, 1)
        self.plotEllipsometryCB = QtWidgets.QCheckBox(self.groupBox_6)
        self.plotEllipsometryCB.setEnabled(False)
        self.plotEllipsometryCB.setText("")
        self.plotEllipsometryCB.setObjectName("plotEllipsometryCB")
        self.gridLayout.addWidget(self.plotEllipsometryCB, 6, 1, 1, 1)
        self.verticalLayout_16.addWidget(self.groupBox_6)
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.plotOptBeamCB = QtWidgets.QCheckBox(self.groupBox_7)
        self.plotOptBeamCB.setText("")
        self.plotOptBeamCB.setObjectName("plotOptBeamCB")
        self.gridLayout_5.addWidget(self.plotOptBeamCB, 1, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.groupBox_7)
        self.label_21.setObjectName("label_21")
        self.gridLayout_5.addWidget(self.label_21, 0, 1, 1, 1)
        self.calcOptBeamCB = QtWidgets.QCheckBox(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calcOptBeamCB.sizePolicy().hasHeightForWidth())
        self.calcOptBeamCB.setSizePolicy(sizePolicy)
        self.calcOptBeamCB.setObjectName("calcOptBeamCB")
        self.gridLayout_5.addWidget(self.calcOptBeamCB, 1, 0, 1, 1)
        self.verticalLayout_16.addWidget(self.groupBox_7)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_16.addItem(spacerItem6)
        self.tabWidget_2.addTab(self.tab_3, "")
        self.verticalLayout_13.addWidget(self.tabWidget_2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.splitter)
        self.dockStackSetup.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockStackSetup)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.DockResults = QtWidgets.QDockWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DockResults.sizePolicy().hasHeightForWidth())
        self.DockResults.setSizePolicy(sizePolicy)
        self.DockResults.setMinimumSize(QtCore.QSize(823, 217))
        self.DockResults.setFloating(False)
        self.DockResults.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.DockResults.setAllowedAreas(QtCore.Qt.BottomDockWidgetArea|QtCore.Qt.RightDockWidgetArea|QtCore.Qt.TopDockWidgetArea)
        self.DockResults.setObjectName("DockResults")
        self.dockWidgetContents_3 = QtWidgets.QWidget()
        self.dockWidgetContents_3.setObjectName("dockWidgetContents_3")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.dockWidgetContents_3)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.splitter_2 = QtWidgets.QSplitter(self.dockWidgetContents_3)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setOpaqueResize(True)
        self.splitter_2.setChildrenCollapsible(False)
        self.splitter_2.setObjectName("splitter_2")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.splitter_2)
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.ResultTableView = QtWidgets.QTableView(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ResultTableView.sizePolicy().hasHeightForWidth())
        self.ResultTableView.setSizePolicy(sizePolicy)
        self.ResultTableView.setMinimumSize(QtCore.QSize(300, 0))
        self.ResultTableView.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.ResultTableView.setAlternatingRowColors(True)
        self.ResultTableView.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.ResultTableView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.ResultTableView.setSortingEnabled(False)
        self.ResultTableView.setObjectName("ResultTableView")
        self.verticalLayout_3.addWidget(self.ResultTableView)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.deleteResult = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.deleteResult.setObjectName("deleteResult")
        self.horizontalLayout_8.addWidget(self.deleteResult)
        self.ConfigTableView = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.ConfigTableView.setObjectName("ConfigTableView")
        self.horizontalLayout_8.addWidget(self.ConfigTableView)
        self.reopenStack = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.reopenStack.setObjectName("reopenStack")
        self.horizontalLayout_8.addWidget(self.reopenStack)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.splitter_2)
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.CurveTreeWidget = QtWidgets.QTreeWidget(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CurveTreeWidget.sizePolicy().hasHeightForWidth())
        self.CurveTreeWidget.setSizePolicy(sizePolicy)
        self.CurveTreeWidget.setMinimumSize(QtCore.QSize(100, 0))
        self.CurveTreeWidget.setMidLineWidth(1)
        self.CurveTreeWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.CurveTreeWidget.setObjectName("CurveTreeWidget")
        self.CurveTreeWidget.headerItem().setText(0, "1")
        self.CurveTreeWidget.header().setVisible(False)
        self.verticalLayout_4.addWidget(self.CurveTreeWidget)
        self.plotCurve = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.plotCurve.setObjectName("plotCurve")
        self.verticalLayout_4.addWidget(self.plotCurve)
        self.horizontalLayout_14.addWidget(self.splitter_2)
        self.DockResults.setWidget(self.dockWidgetContents_3)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.DockResults)

        self.retranslateUi(MainWindow)
        self.tabWidget_2.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(1)
        self.stackedWidget.setCurrentIndex(2)
        self.colSourceArea.setCurrentIndex(1)
        self.calcStackOpticsCB.toggled['bool'].connect(self.calcFieldIntensityCB.setEnabled)
        self.calcFieldIntensityCB.toggled['bool'].connect(self.calcLayerwiseOpticsCB.setEnabled)
        self.calcLayerwiseOpticsCB.toggled['bool'].connect(self.calcGenerationCB.setEnabled)
        self.calcEllipsometryCB.toggled['bool'].connect(self.plotEllipsometryCB.setEnabled)
        self.calcGenerationCB.toggled['bool'].connect(self.plotGenerationCB.setEnabled)
        self.calcQECB.toggled['bool'].connect(self.plotQECB.setEnabled)
        self.calcLayerwiseOpticsCB.toggled['bool'].connect(self.plotLayerwiseOpticsCB.setEnabled)
        self.calcFieldIntensityCB.toggled['bool'].connect(self.plotFieldIntensityCB.setEnabled)
        self.calcStackOpticsCB.toggled['bool'].connect(self.plotStackOpticsCB.setEnabled)
        self.calcOptBeamCB.toggled['bool'].connect(self.plotOptBeamCB.setEnabled)
        self.calcLayerwiseOpticsCB.toggled['bool'].connect(self.calcQECB.setEnabled)
        self.criSourceSelection.currentIndexChanged['int'].connect(self.stackedWidget.setCurrentIndex)
        self.collectionSelection.currentIndexChanged['int'].connect(self.colSourceArea.setCurrentIndex)
        self.constantPointsRB.toggled['bool'].connect(self.constantPointsSB.setEnabled)
        self.constantDistRB.toggled['bool'].connect(self.constantDistSB.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.dockStackSetup.setWindowTitle(_translate("MainWindow", "stack definition"))
        self.label_5.setText(_translate("MainWindow", "stack Name:"))
        self.StackNameEdit.setText(_translate("MainWindow", "Stack"))
        self.groupBox.setTitle(_translate("MainWindow", "Layer details"))
        self.label_2.setText(_translate("MainWindow", "name:"))
        self.label_3.setText(_translate("MainWindow", "thickness:"))
        self.layerThicknessUnit.setText(_translate("MainWindow", "nm"))
        self.colorButton.setText(_translate("MainWindow", "color"))
        self.thickLayerCB.setText(_translate("MainWindow", "incoherent"))
        self.groupBox_2.setTitle(_translate("MainWindow", "complex refractive index"))
        self.label_8.setText(_translate("MainWindow", "source:"))
        self.label_11.setText(_translate("MainWindow", "material:"))
        self.label_12.setText(_translate("MainWindow", "file:"))
        self.criFilePathButton.setText(_translate("MainWindow", "..."))
        self.criFileGroupBox.setTitle(_translate("MainWindow", "alpha only"))
        self.label_13.setText(_translate("MainWindow", "constant refractive index n:"))
        self.label_14.setText(_translate("MainWindow", "refractive index n:"))
        self.label_15.setText(_translate("MainWindow", "extinction coefficient:"))
        self.label_18.setText(_translate("MainWindow", "grading function"))
        self.gradingFilesButton.setText(_translate("MainWindow", "append cri files"))
        self.defineDielectricFunc.setText(_translate("MainWindow", "define dielectric function ..."))
        self.showCRI.setText(_translate("MainWindow", "show optical constants"))
        self.extractBandgapPB.setText(_translate("MainWindow", "extract bandgap"))
        self.sroughGroup.setTitle(_translate("MainWindow", "surface roughness"))
        self.label_7.setText(_translate("MainWindow", "thickness (nm):"))
        self.label_10.setText(_translate("MainWindow", "Haze Reflection:"))
        self.hazeRLabel.setText(_translate("MainWindow", "0"))
        self.label_16.setText(_translate("MainWindow", "Haze Transmission:"))
        self.hazeTLabel.setText(_translate("MainWindow", "0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.opticsTab), _translate("MainWindow", "optical"))
        self.groupBox_3.setTitle(_translate("MainWindow", "carrier collection"))
        self.label_9.setText(_translate("MainWindow", "collection function:"))
        self.label_17.setText(_translate("MainWindow", "collection function:"))
        self.SCRtop.setText(_translate("MainWindow", "SCR top"))
        self.label_22.setText(_translate("MainWindow", "space charge region width [nm]"))
        self.label_23.setText(_translate("MainWindow", "diffusion length [nm]"))
        self.label_19.setText(_translate("MainWindow", "liinear grading [meV/mum]"))
        self.label_4.setText(_translate("MainWindow", "surface rec. velocity [cm/s]"))
        self.SCRbottom.setText(_translate("MainWindow", "SCR bottom"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.electricsTab), _translate("MainWindow", "electrical"))
        self.groupBox_5.setTitle(_translate("MainWindow", "depth sampling points"))
        self.constantPointsRB.setText(_translate("MainWindow", "constant no of points"))
        self.constantDistRB.setText(_translate("MainWindow", "constant depth step (nm)"))
        self.autoDistRB.setText(_translate("MainWindow", "automatic (interface refinement)"))
        self.meshLabel.setText(_translate("MainWindow", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "mesh"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_2), _translate("MainWindow", "setup"))
        self.groupBox_6.setTitle(_translate("MainWindow", "GTMM"))
        self.calcGenerationCB.setText(_translate("MainWindow", "generation rate"))
        self.calcStackOpticsCB.setText(_translate("MainWindow", "stack optics (A,R,T)"))
        self.calcFieldIntensityCB.setText(_translate("MainWindow", "local field intensity"))
        self.calcLayerwiseOpticsCB.setText(_translate("MainWindow", "layerwise optics (absorption, collection)"))
        self.calcQECB.setText(_translate("MainWindow", "QE"))
        self.label_20.setText(_translate("MainWindow", "plot"))
        self.calcEllipsometryCB.setText(_translate("MainWindow", "ellipsometric values (angle > 0°)"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Lambert-Beer"))
        self.label_21.setText(_translate("MainWindow", "plot"))
        self.calcOptBeamCB.setText(_translate("MainWindow", "Lamber-Beer Optics"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("MainWindow", "simulation"))
        self.DockResults.setWindowTitle(_translate("MainWindow", "results"))
        self.label_6.setText(_translate("MainWindow", "calculated stacks"))
        self.deleteResult.setText(_translate("MainWindow", "delete result"))
        self.ConfigTableView.setText(_translate("MainWindow", "config view"))
        self.reopenStack.setText(_translate("MainWindow", "re-open stack"))
        self.label.setText(_translate("MainWindow", "available curves"))
        self.plotCurve.setText(_translate("MainWindow", "plot curve"))

from ui.scientificspin import ScientificDoubleSpinBox
from ui.mplwidgetsimple import MplWidgetSimple

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

