# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'L:\05_Python\OptiSim V0.4.0\ui\references.ui'
#
# Created: Fri Nov 20 10:38:57 2015
#      by: PyQt5 UI code generator 5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(627, 290)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 3, 1, 1)
        self.R_LE = QtWidgets.QLineEdit(Dialog)
        self.R_LE.setObjectName("R_LE")
        self.gridLayout.addWidget(self.R_LE, 1, 1, 1, 1)
        self.R_PB = QtWidgets.QPushButton(Dialog)
        self.R_PB.setObjectName("R_PB")
        self.gridLayout.addWidget(self.R_PB, 1, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 1, 1, 1)
        self.R_CB = QtWidgets.QCheckBox(Dialog)
        self.R_CB.setText("")
        self.R_CB.setObjectName("R_CB")
        self.gridLayout.addWidget(self.R_CB, 1, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.psi_CB = QtWidgets.QCheckBox(Dialog)
        self.psi_CB.setText("")
        self.psi_CB.setObjectName("psi_CB")
        self.gridLayout.addWidget(self.psi_CB, 6, 3, 1, 1)
        self.T_LE = QtWidgets.QLineEdit(Dialog)
        self.T_LE.setObjectName("T_LE")
        self.gridLayout.addWidget(self.T_LE, 3, 1, 1, 1)
        self.EQE_CB = QtWidgets.QCheckBox(Dialog)
        self.EQE_CB.setText("")
        self.EQE_CB.setObjectName("EQE_CB")
        self.gridLayout.addWidget(self.EQE_CB, 4, 3, 1, 1)
        self.EQE_PB = QtWidgets.QPushButton(Dialog)
        self.EQE_PB.setObjectName("EQE_PB")
        self.gridLayout.addWidget(self.EQE_PB, 4, 2, 1, 1)
        self.T_CB = QtWidgets.QCheckBox(Dialog)
        self.T_CB.setText("")
        self.T_CB.setObjectName("T_CB")
        self.gridLayout.addWidget(self.T_CB, 3, 3, 1, 1)
        self.psi_PB = QtWidgets.QPushButton(Dialog)
        self.psi_PB.setObjectName("psi_PB")
        self.gridLayout.addWidget(self.psi_PB, 6, 2, 1, 1)
        self.psi_LE = QtWidgets.QLineEdit(Dialog)
        self.psi_LE.setObjectName("psi_LE")
        self.gridLayout.addWidget(self.psi_LE, 6, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 6, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.EQE_LE = QtWidgets.QLineEdit(Dialog)
        self.EQE_LE.setObjectName("EQE_LE")
        self.gridLayout.addWidget(self.EQE_LE, 4, 1, 1, 1)
        self.T_PB = QtWidgets.QPushButton(Dialog)
        self.T_PB.setObjectName("T_PB")
        self.gridLayout.addWidget(self.T_PB, 3, 2, 1, 1)
        self.delta_PB = QtWidgets.QPushButton(Dialog)
        self.delta_PB.setObjectName("delta_PB")
        self.gridLayout.addWidget(self.delta_PB, 8, 2, 1, 1)
        self.delta_CB = QtWidgets.QCheckBox(Dialog)
        self.delta_CB.setText("")
        self.delta_CB.setObjectName("delta_CB")
        self.gridLayout.addWidget(self.delta_CB, 8, 3, 1, 1)
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 8, 0, 1, 1)
        self.delta_LE = QtWidgets.QLineEdit(Dialog)
        self.delta_LE.setObjectName("delta_LE")
        self.gridLayout.addWidget(self.delta_LE, 8, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Reference definition"))
        self.label_4.setText(_translate("Dialog", "plot"))
        self.R_PB.setText(_translate("Dialog", "load"))
        self.label_3.setText(_translate("Dialog", "file"))
        self.label_2.setText(_translate("Dialog", "reference type"))
        self.label.setText(_translate("Dialog", "reflection spectra"))
        self.EQE_PB.setText(_translate("Dialog", "load"))
        self.psi_PB.setText(_translate("Dialog", "load"))
        self.label_6.setText(_translate("Dialog", "external quantum efficiency"))
        self.label_7.setText(_translate("Dialog", "ellipsometry psi"))
        self.label_5.setText(_translate("Dialog", "transmittance spectra"))
        self.T_PB.setText(_translate("Dialog", "load"))
        self.delta_PB.setText(_translate("Dialog", "load"))
        self.label_8.setText(_translate("Dialog", "ellipsometry delta"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

